#database configuration
server:
  port: 8083
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bankingmanagement
    username: root
    password: carnew290
