server:
  port: 8082
logging:
  level:
    org:
      springframework: info
    com:
      bankingmanagementapi: debug
  file:
    name: bankingmanagementapi.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: info,health,metrics,loggers,beans,mappings,threaddump,env,caches
  endpoint:
    health:
      show-details: always
