server:
  port: 8084

#dbconnection
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sys
    username: root
    password: carnew290

management:
  endpoints:
    web:
      exposure:
        include: info,health,metrics,loggers,beans,mappings,threaddump,env,caches
  endpoint:
    health:
      show-details: always
